### ISSUE TITLE
Superstedfesting

### ISSUE THREAD

**Issue by jetgeo** [vegvesen/SOSI-Vegnett#70]
Stedfesting av lenker fra detaljert nivå på vegtrasenivå. Standardiseres under SOSI Vegnett eller SOSI Nettverk og lineære referanser?

**Comment by jetgeo** [comment]
Håndteres foreløpig som en intern NVDB-sak. Trenger ikke å inngå i SOSI Vegnett 5.0 eller Elveg. Foreslås eventuelt standardisert som en del av neste versjon av Nettverk og lineære referanser. 
Avklares på prosjektmøte 2.

**Comment by LindaStoeng** [comment]
i prosjektmøte 2  25. september ble vi enige om at vi skal ta dette med likevel. Vi må derfor finne løsning for dette nå.

**Comment by jetgeo** [comment]
Rettelse; Dette inngår ikke i standarden.
